# Generated by Django 6.0.6 on 2026-06-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_created_at_user_must_change_password_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('COMPANY_ADMIN', 'COMPANY_ADMIN'), ('SITE_ENGINEER', 'SITE_ENGINEER'), ('CONTRACTOR', 'CONTRACTOR'), ('CLIENT', 'CLIENT')], default='CLIENT', max_length=30),
        ),
    ]
