# Generated by Django 6.0.6 on 2026-06-23 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snags', '0002_snag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnagImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='snags/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('snag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='snags.snag')),
            ],
        ),
    ]
